version: "3.8"

services:
  aria2-pro:
    image: p3terx/aria2-pro
    container_name: home-aria2
    hostname: home-aria2
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/downloads:/downloads
    ports:
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - traefik_proxy    
    labels:
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.aria2.tls=true
      - traefik.http.routers.aria2.entrypoints=websecure
      - traefik.http.routers.aria2.rule=Host(`aria2.home.local`)
      - traefik.http.services.aria2.loadbalancer.server.port=6800

  ariang:
    image: p3terx/ariang
    container_name: home-ariang
    hostname: home-ariang
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - traefik_proxy
    labels:
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.ariang.tls=true
      - traefik.http.routers.ariang.rule=Host(`ariang.home.local`)
      - traefik.http.services.ariang.loadbalancer.server.port=6880

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
