entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

ping:
  entryPoint: websecure

providers:
  file:
    filename: /etc/traefik/traefik.dynamic.yml
    watch: true

  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik_proxy"
    swarmMode: false
    watch: true

api:
  dashboard: true

log:
  level: INFO
  filePath: /var/log/traefik/debug.log
  format: json
accessLog:
  filePath: /var/log/traefik/access.log
  format: json


metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0