version: '3.7'

services:
  netdata:
    image: netdata/netdata:latest-aarch64
    container_name: home-netdata
    hostname: home-netdata
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_proxy
    environment:
      - DOCKER_HOST=proxy:2375
    labels:
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.netdata.tls=true
      - traefik.http.routers.netdata.rule=Host(`netdata.home.local`)
      - traefik.http.services.netdata.loadbalancer.server.port=19999

  proxy:
    image: tecnativa/docker-socket-proxy
    container_name: home-netdata-proxy
    hostname: home-netdata-proxy
    restart: always
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
